Migrate to kubebuilder v3
cybozu-go/contour-plus pull request #59
Opened 2021-04-15 07:25 UTC by ysksuzuki

Signed-off-by: Yusuke Suzuki <yusuke-suzuki@cybozu.co.jp>

2021-04-16 06:56 UTC, morimoto-cybozu commented on config/rbac/role_binding.yaml
> +  name: manager-rolebinding
This name seems too generic.
Will this be changed or prefixed when deployed in our environment?

2021-04-16 06:59 UTC, morimoto-cybozu commented on config/rbac/role_binding.yaml
> +  name: manager-rolebinding
I confirmed `namePrefix: contour-plus-` in config/default/kustomization.yaml.

2021-04-16 07:49 UTC, morimoto-cybozu commented
@ysksuzuki 
`kustomize build` like below fails in my environment, even on the main branch.  Am I missing something?

```
make crds
make kustomize
./bin/kustomize build ./config/default/
```

2021-04-16 08:22 UTC, ysksuzuki commented
@morimoto-cybozu 
I think we should remove [this line](https://github.com/cybozu-go/contour-plus/blob/k8s-1.20/config/default/kustomization.yaml#L16), because contour-plus doesn't offer any CRDs. `config` directory only contains third party CRDs for env test.

2021-04-16 10:03 UTC, morimoto-cybozu requested changes

2021-04-16 10:03 UTC, morimoto-cybozu commented on config/default/kustomization.yaml
>  - ../crd
This prevents `kustomize build config/default`.

2021-04-16 10:03 UTC, morimoto-cybozu commented on config/default/kustomization.yaml
> +# crd/kustomization.yaml
I can't find `[WEBHOOK]` sections other than in this YAML file.

2021-04-19 05:39 UTC, morimoto-cybozu approved these changes
LGTM

2021-04-19 05:39 UTC, merged